name: Build and Push Docker Image with Jib

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Build and Push Docker Image
      run: ./gradlew jib --image="${{ secrets.ECR_IMAGE_URI }}"
      
    - name: CURL destroy request to Terraform Cloud
      run: |
        curl -X POST https://app.terraform.io/api/v2/runs \
        -H "Content-Type: application/vnd.api+json" \
        -H "Authorization: Bearer ${{ secrets.TERRAFORM_CLOUD_TOKEN }}" \
        -d '{
          "data": {
            "attributes": {
              "is-destroy": true,
              "message": "Triggered via destroy API"
            },
            "type":"runs",
            "relationships": {
              "workspace": {
                "data": {
                  "type": "workspaces",
                  "id": "${{ secrets.TERRAFORM_WORKSPACE_ID }}"
                }
              }
            }
          }
        }'

    - name: CURL apply request to Terraform Cloud
      run: |
        curl -X POST https://app.terraform.io/api/v2/runs \
        -H "Content-Type: application/vnd.api+json" \
        -H "Authorization: Bearer ${{ secrets.TERRAFORM_CLOUD_TOKEN }}" \
        -d '{
          "data": {
            "attributes": {
              "message": "Triggered via apply API"
            },
            "type":"runs",
            "relationships": {
              "workspace": {
                "data": {
                  "type": "workspaces",
                  "id": "${{ secrets.TERRAFORM_WORKSPACE_ID }}"
                }
              }
            }
          }
        }'
